# Generated by Django 5.0.6 on 2025-01-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userdata_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="isPrivacyPolicyAccepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userdata",
            name="isTermsAccepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userdata",
            name="privacyLevel",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("protected", "Protected"),
                ],
                default="public",
                max_length=10,
            ),
        ),
    ]
