# Generated by Django 5.0.6 on 2025-01-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userdata_isprivacypolicyaccepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="date_of_birth",
            field=models.DateField(default="2000-02-07"),
        ),
    ]
